// <auto-generated />
using System;
using McGurkin.Api.Features.Kv.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McGurkin.Api.Features.Kv.Data.Migrations
{
    [DbContext(typeof(KvDbContext))]
    [Migration("20250424182853_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kv")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("McGurkin.Api.Features.Tmdb.Data.UserProfile", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ShowAllChannels")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowRated")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowWatchList")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserProfileId");

                    b.ToTable("UserProfiles", "kv");
                });

            modelBuilder.Entity("McGurkin.Api.Features.Tmdb.Data.UserProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserProviders", "kv");
                });

            modelBuilder.Entity("McGurkin.Api.Features.Tmdb.Data.UserRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserRatings", "kv");
                });

            modelBuilder.Entity("McGurkin.Api.Features.Tmdb.Data.UserProvider", b =>
                {
                    b.HasOne("McGurkin.Api.Features.Tmdb.Data.UserProfile", null)
                        .WithMany("UserProviders")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McGurkin.Api.Features.Tmdb.Data.UserRating", b =>
                {
                    b.HasOne("McGurkin.Api.Features.Tmdb.Data.UserProfile", null)
                        .WithMany("UserRatings")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McGurkin.Api.Features.Tmdb.Data.UserProfile", b =>
                {
                    b.Navigation("UserProviders");

                    b.Navigation("UserRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
